version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Install deps
          command: dpkg --add-architecture i386 && apt-get update && apt-get install -y git cmake pkg-config qtbase5-dev qtwebengine5-dev libssl-dev:i386 libcurl4-openssl-dev libcurl4-openssl-dev:i386 g++-multilib libpng-dev:i386 libx11-dev:i386 libxi-dev:i386 libssl-dev libudev-dev:i386 libevdev-dev:i386 libegl1-mesa-dev:i386 libgl1-mesa-dev libssl-dev libuv1-dev libzip-dev libprotobuf-dev protobuf-compiler qtdeclarative5-dev libqt5svg5-dev qml-module-qtquick2 qml-module-qtquick-layouts qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-window2 qml-module-qtquick-dialogs qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel
      - run:
          name: Run the buildscript
          command: ./build.sh -j4
      - store_artifacts:
          path: output
          destination: /
      - run:
          name: Upload files to repo
          command: .circleci/deploy-debs.sh deb-ubuntu bionic output
  build-xenial:
    docker:
      - image: minecraftlinux/ci-xenial:0.0.1
    steps:
      - checkout
      - run:
          name: Run the buildscript
          command: . /opt/qt59/bin/qt59-env.sh && ./build.sh -j4 -q quirks-ubuntu-1604.sh
      - store_artifacts:
          path: output
          destination: /
      - run:
          name: Upload files to repo
          command: .circleci/deploy-debs.sh deb-ubuntu xenial output
  build-appimage:
    docker:
      - image: minecraftlinux/ci-xenial:0.0.1
    steps:
      - checkout
      - run:
          name: Run the buildscript
          command: . /opt/qt59/bin/qt59-env.sh && ./build_appimage.sh -j4 -q quirks-ubuntu-1604.sh
      - store_artifacts:
          path: output
          destination: /
      - run:
          name: Upload the .AppImage to website
          command: 'curl -X POST -u "ci:$WEBSITE_CI_UPLOAD_PASS" --data-binary "@output/Minecraft_Bedrock_Launcher-x86_64.dmg" -H "X-Type: appimage" https://mcpelauncher.mrarm.io/api/v1/upload'
      - run:
          name: Update version number
          command: 'curl -X POST -u "ci:$WEBSITE_CI_UPLOAD_PASS" -F "channel=appimage" -F "build_id=$CIRCLE_BUILD_NUM" https://mcpelauncher.mrarm.io/api/v1/version'
workflows:
  version: 2
  build:
    jobs:
      - build
      - build-xenial
      - build-appimage
