name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download solus 4.1
      run: curl http://solus.veatnet.de/iso/images/4.1/Solus-4.1-Budgie.iso -o Solus.iso
    - name: Install Solus
      run: |
        mkdir iso
        mount Solus.iso iso/
        mkdir LiveOS
        mount iso/LiveOS/squashfs.img LiveOS/
        mkdir rootfs
        mount LiveOS/LiveOS/rootfs.img rootfs/
        rsync --progress -ptgo -A -X -r --links /media/christopher/6e41190a-9de6-4eda-aa98-12622b5a0d4b/ manjaro/
        mkdir root
        mkdir -p root/root
        mount --bind $PWD root/root
        mount --bind /proc root/proc
        mount --bind /dev root/dev
        chroot root/ 'sudo eopkg install -c system.devel'
        chroot root/ 'sudo eopkg install git mesalib-32bit-devel openssl-32bit-devel curl-32bit-devel libpng-32bit-devel libx11-32bit-devel gcc g++ libgcc-32bit libstdc++-32bit cmake make binutils glibc-32bit-devel libgudev-32bit-devel libxi-32bit-devel'
    - name: Compile Launcher
      run: |
        chroot root/ '(git clone https://gitlab.freedesktop.org/libevdev/libevdev.git || cd libevdev && git pull) && cd libevdev && ./autogen.sh CFLAGS=-m32 && make && sudo make install && ln -s /usr/local/lib/libevdev.so.2 /usr/lib32/libevdev.so.2 || :'
        chroot root/ '(git clone --recursive https://github.com/ChristopherHX/mcpelauncher-manifest.git mcpelauncher || cd mcpelauncher && git pull) && cd mcpelauncher && mkdir -p build && cd build && cmake .. -DCMAKE_ASM_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 && make && sudo make install || :'
