name: CI
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
jobs:
  buildbusterappimage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run -e GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} -v $PWD/ldd:/usr/bin/ldd -v $PWD:$PWD -w $PWD --rm buildpack-deps:buster bash -c "dpkg --add-architecture i386 && dpkg --add-architecture armhf && apt update && DEBIAN_FRONTEND=noninteractive apt install -y chrpath libatomic1:armhf python3-pip wget cmake g++-arm-linux-gnueabihf patchelf libegl1-mesa:i386 zlib1g:i386 libstdc++6:i386 libgl1-mesa-dri:i386 libasound2:i386 pulseaudio:i386 libpng-dev:armhf libx11-dev:armhf libxi-dev:armhf libcurl4-openssl-dev:armhf libudev-dev:armhf libevdev-dev:armhf libegl1-mesa-dev:armhf libasound2:armhf qt5-default:armhf git cmake pkg-config qtbase5-dev:armhf qtwebengine5-dev:armhf libssl-dev:armhf libcurl4-openssl-dev:armhf libpng-dev:armhf libx11-dev:armhf libxi-dev:armhf libssl-dev:armhf libudev-dev:armhf libevdev-dev:armhf libegl1-mesa-dev:armhf libgl1-mesa-dev:armhf libssl-dev:armhf libuv1-dev:armhf libzip-dev:armhf libprotobuf-dev:armhf protobuf-compiler qtdeclarative5-dev:armhf libqt5svg5-dev:armhf qml-module-qtquick2:armhf qml-module-qtquick-layouts:armhf qml-module-qtquick-controls:armhf qml-module-qtquick-controls2:armhf qml-module-qtquick-window2:armhf qml-module-qtquick-dialogs:armhf qml-module-qt-labs-settings:armhf qml-module-qt-labs-folderlistmodel:armhf jq curl binutils desktop-file-utils squashfs-tools qtdeclarative5-dev-tools:armhf && pip3 install jinja2 ds_store ply && QMAKE=/usr/bin/arm-linux-gnueabihf-qmake PATH=/usr/lib/arm-linux-gnueabihf/qt5/bin/:$PATH NO_STRIP=1 ./build_appimage_armhf2.sh -j4 -u https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ARM.AppImage/version.armhfbuster -i ${GITHUB_RUN_NUMBER}"
    - name: Generate update info
      run: |
        cd output
        file=(*.AppImage)
        sudo bash -c "echo build_id=${GITHUB_RUN_NUMBER}$'\n'download_url=https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ARM.AppImage/${file} > version.armhfbuster" || :
    - uses: actions/upload-artifact@v1
      with:
        name: armhfappimagebuster
        path: output/
  buildbusterappimage64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run -e GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} -v $PWD/ldd:/usr/bin/ldd -v $PWD:$PWD -w $PWD --rm buildpack-deps:buster bash -c "dpkg --add-architecture arm64 && dpkg --add-architecture armhf && apt update && DEBIAN_FRONTEND=noninteractive apt install -y chrpath libatomic1:armhf libatomic1:arm64 python3-pip wget cmake g++-arm-linux-gnueabihf g++-aarch64-linux-gnu patchelf libpng-dev:armhf libx11-dev:armhf libxi-dev:armhf libcurl4-openssl-dev:armhf libudev-dev:armhf libevdev-dev:armhf libegl1-mesa-dev:armhf libasound2:armhf qt5-default:arm64 git cmake pkg-config qtbase5-dev:arm64 qtwebengine5-dev:arm64 libssl-dev:arm64 libcurl4-openssl-dev:arm64 libpng-dev:arm64 libx11-dev:arm64 libxi-dev:arm64 libssl-dev:arm64 libudev-dev:arm64 libevdev-dev:arm64 libegl1-mesa-dev:arm64 libgl1-mesa-dev:arm64 libssl-dev:arm64 libuv1-dev:arm64 libzip-dev:arm64 libprotobuf-dev:arm64 protobuf-compiler qtdeclarative5-dev:arm64 libqt5svg5-dev:arm64 qml-module-qtquick2:arm64 qml-module-qtquick-layouts:arm64 qml-module-qtquick-controls:arm64 qml-module-qtquick-controls2:arm64 qml-module-qtquick-window2:arm64 qml-module-qtquick-dialogs:arm64 qml-module-qt-labs-settings:arm64 qml-module-qt-labs-folderlistmodel:arm64 jq curl binutils desktop-file-utils squashfs-tools qtdeclarative5-dev-tools:arm64 && pip3 install jinja2 ds_store ply && QMAKE=/usr/bin/aarch64-linux-gnu-qmake PATH=/usr/lib/aarch64-linux-gnu/qt5/bin/:$PATH NO_STRIP=1 ./build_appimage_arm64.sh -j4 -u https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ARM.AppImage/version.arm64buster -i ${GITHUB_RUN_NUMBER}"
    - name: Generate update info
      run: |
        cd output
        file=(*.AppImage)
        sudo bash -c "echo build_id=${GITHUB_RUN_NUMBER}$'\n'download_url=https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/ARM.AppImage/${file} > version.arm64buster" || :
    - uses: actions/upload-artifact@v1
      with:
        name: arm64appimagebuster
        path: output/
  uploadlatest:
    runs-on: ubuntu-latest
    needs: [buildbusterappimage, buildbusterappimage64]
    steps:
    - name: Download armhfappimagebuster
      uses: actions/download-artifact@v1
      with:
        name: armhfappimagebuster
    - name: Download arm64appimagebuster
      uses: actions/download-artifact@v1
      with:
        name: arm64appimagebuster
    - name: Move to artifacts
      run: mkdir -p artifacts && mv armhfappimagebuster/*.AppImage armhfappimagebuster/version.* arm64appimagebuster/*.AppImage arm64appimagebuster/version.* ./artifacts/
    - name: Upload Latest
      run: curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz --output ghr.tar.gz && tar -xf ghr.tar.gz && ./ghr*/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ChristopherHX -r linux-packaging-scripts -delete -b "**Note Experimental AppImage's ahead**,"$'\n'"Only the armhf one is partially Tested on Raspberry Pi2**" ARM.AppImage artifacts
