name: Containers

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: minecraftlinux/ci-xenial:0.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Download deps
      shell: /bin/bash
      run: |
        curl -L http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz --output llvm.tar.xz
        tar --no-same-owner -xf llvm.tar.xz
        curl -L https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz --output cmake.tar.gz
        tar --no-same-owner -xf cmake.tar.gz
        apt update
        DEBIAN_FRONTEND=noninteractive apt -y install wget g++-multilib texinfo apt-transport-https vim-common desktop-file-utils
        bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        DEBIAN_FRONTEND=noninteractive apt -y install libc++-10-dev:i386 libc++abi-10-dev:i386 libegl1-mesa-dev:i386 zsync
    - name: Run the buildscript
      shell: /bin/bash
      run: |
        . /opt/qt59/bin/qt59-env.sh
        export PATH=$PWD/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PWD/cmake-3.16.2-Linux-x86_64/bin:$PATH
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH+"${LD_LIBRARY_PATH}:"}$PWD/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04/lib
        export CC=clang
        export CXX=clang++
        ./build_appimage.sh -j4 -q quirks-ubuntu-1604.sh -k "zsync|https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/appimage/version.x86_64.zsync" -i ${CIRCLE_BUILD_NUM}
    - name: create update info
      shell: /bin/bash
      run: |
        cd output
        file=(*.AppImage)
        echo build_id=${CIRCLE_BUILD_NUM}$'\n'download_url=https://github.com/ChristopherHX/linux-packaging-scripts/releases/download/appimage/${file} > version.amd64
    - uses: actions/upload-artifact@v1
      with:
        name: x86_64.AppImage
        path: output/
    - name: Upload
      shell: /bin/bash
      run: |
        curl -L https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz --output ghr.tar.gz
        tar -xf ghr.tar.gz
        ./ghr*/ghr -t ${{ secrets.GITHUB_TOKEN }} -u ChristopherHX -r linux-packaging-scripts -replace appimage output/